[packages]

[packages.darwin]
brew = [
  "btop",
  "fd",
  "git",
  "gpg",
  "httpie",
  "opencode",
  "zsh"
]
cask = [
  "firefox",
  "font-jetbrains-mono-nerd-font",
  "font-zed-mono-nerd-font",
  "ghostty",
  "google-chrome",
  "linearmouse",
  "raycast",
  "visual-studio-code",
  "whatsapp",
]

[packages.linux]
apt = [
  "git",
  "zsh"
]

[packages.mise]
bun = "latest"
deno = "latest"
fzf = "latest"
github-cli = "latest"
lazygit = "latest"
rust = "latest"
starship = "latest"
swift = "latest"
uv = "latest"
zoxide = "latest"

[packages.others]
rad = "https://radicle.xyz/install"
